sudo: required
services :
  - docker

before_install:
  - docker build -t sfnanjum/docker-react -f Dockerfile.dev .

script:
  - npm uninstall babel-jest@24.8.0
  - docker run sfnanjum/docker-react npm run test -- -- coverage